### ISSUE TITLE
Plugin does not load without core jar deployed

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-metrics-reporter#13] opened 2016-12-05 16:56 UTC
A reporter plugin is supposed to load without the `metrics-reporter-core-x.x.x.jar` in the `plugins/` folder but it does not. This is 100% reproducible on my setup and two customers had the same issue but not on @joschi's setup.

```
lennart@graylog-srv01:/usr/share/graylog-server/plugin$ unzip -l metrics-reporter-datadog-1.4.0.jar | grep org/graylog/plugins/metrics/core
        0  2016-10-28 15:25   org/graylog/plugins/metrics/core/
     1491  2016-10-28 15:25   org/graylog/plugins/metrics/core/BasePluginMetaData.class
        0  2016-10-28 15:25   org/graylog/plugins/metrics/core/jadconfig/
     2708  2016-10-28 15:25   org/graylog/plugins/metrics/core/jadconfig/StringMapConverter.class
     3594  2016-10-28 15:25   org/graylog/plugins/metrics/core/jadconfig/PatternListConverter.class
     1423  2016-10-28 15:25   org/graylog/plugins/metrics/core/RegexMetricFilter.class
```

Plugin version 1.4.0
Graylog 2.1.2+50e449a
openjdk version "1.8.0_111"

**Comment by jalogisch** [comment] 2016-12-06 13:49
*metrics-reporter-gelf-1.4.0.jar* is working without core 

* ubuntu 16.04 
* openjdk version "1.8.0_111"

**Comment by joschi** [comment] 2016-12-20 10:56
@lennartkoopmann Since this couldn't be reproduced, I'm closing this issue.

**Closed as completed by joschi** 2016-12-20 10:56 UTC
